/** Kazakh labels for ready collections (chips, catalog groups). */

export const COLLECTION_GROUP_KK = {
  tops: 'Топтар',
  movies: 'Фильмдер',
  series: 'Сериалдар',
  'animated-series': 'Мультсериалдар',
  anime: 'Аниме',
  genres: 'Жанрлар',
  mood: 'Көңіл-күй',
  themes: 'Тақырыптар',
  countries: 'Елдер'
};

export const COLLECTION_LABELS_KK = {
  'most-popular': { shortTitle: 'Танымал', desc: 'Қазір барлығы айтып жүр' },
  'best-recent': { shortTitle: 'Жылдардағы үздіктер', desc: 'Жоғары бағалар' },
  'highest-grossing': { shortTitle: 'Кассалық', desc: 'Прокат хиттері' },
  'top-series': { shortTitle: 'Сериалдар', desc: 'Үздік шоулар' },
  'popular-now': { shortTitle: 'Қазір танымал', desc: 'Барлығы айтып жүр' },
  'new-releases': { shortTitle: 'Жаңалықтар', desc: 'Жаңа премьералар' },
  'high-rating': { shortTitle: 'Жоғары рейтинг', desc: '7.5+ баға' },
  'underrated': { shortTitle: 'Бағаланбаған', desc: 'Жақсы, бірақ көрінбеген' },
  'best-all-time': { shortTitle: 'Үздік фильмдер', desc: 'Киноның алтын қоры' },
  'popular-movies': { shortTitle: 'Танымал', desc: 'Қазір барлығы айтып жүр' },
  'new-movies': { shortTitle: 'Жаңалықтар', desc: 'Жаңа премьералар' },
  'feel-evening': { shortTitle: 'Кешке', desc: 'Көңіл-күйге сай' },
  'family': { shortTitle: 'Отбасылық', desc: 'Бүкіл отбасыға' },
  'feel-dark': { shortTitle: 'Қараңғы', desc: 'Ауыр атмосфера' },
  'twist-ending': { shortTitle: 'Твистпен', desc: 'Соңы күтпеген жерден' },
  'theme-travel': { shortTitle: 'Саяхат', desc: 'Жол және ашылулар' },
  'theme-sport': { shortTitle: 'Спорт', desc: 'Жеңістер және мінез' },
  'theme-business': { shortTitle: 'Бизнес', desc: 'Амбициялар және капитал' },
  'theme-school': { shortTitle: 'Мектеп', desc: 'Жастық және есейу' },
  'theme-survival': { shortTitle: 'Өмір сүру', desc: 'Шекарада' },
  'best-series-all-time': { shortTitle: 'Үздік сериалдар', desc: 'Негізгі шоулар' },
  'popular-series': { shortTitle: 'Танымал', desc: 'Қазір барлығы айтып жүр' },
  'new-series': { shortTitle: 'Жаңалықтар', desc: 'Жаңа премьералар' },
  'mini-series': { shortTitle: 'Мини-сериалдар', desc: 'Қысқа оқиғалар' },
  'crime-series': { shortTitle: 'Қылмыс', desc: 'Тергеулер және нуар' },
  'comedy-series': { shortTitle: 'Комедиялар', desc: 'Күлкіге' },
  'drama-series': { shortTitle: 'Драмалар', desc: 'Күшті оқиғалар' },
  'scifi-series': { shortTitle: 'Фантастика', desc: 'Болашақ және басқа әлемдер' },
  'high-rating-series': { shortTitle: 'Жоғары рейтинг', desc: '7.5+ баға' },
  'evening-series': { shortTitle: 'Кешке', desc: 'Жеңіл көру' },
  'best-animated-series': { shortTitle: 'Үздіктер', desc: 'Барлығына арналған анимация' },
  'adult-animated-series': { shortTitle: 'Ересектерге', desc: 'Сатира және қара әзіл' },
  'family-animated-series': { shortTitle: 'Отбасылық', desc: 'Бүкіл отбасыға' },
  'comedy-animated-series': { shortTitle: 'Комедиялар', desc: 'Күлкіге' },
  'adventure-animated-series': { shortTitle: 'Шытырман', desc: 'Үлкен шытырмандар' },
  'scifi-animated-series': { shortTitle: 'Фантастика', desc: 'Болашақ және басқа әлемдер' },
  'superhero-animated-series': { shortTitle: 'Суперқаһармандар', desc: 'Батырлар және командалар' },
  'nostalgic-animated-series': { shortTitle: 'Ностальгия', desc: 'Балалық классика' },
  'like-gravity-falls': { shortTitle: 'Gravity Falls сияқты', desc: 'Жұмбақтар, әзіл, шытырман' },
  'like-rick-and-morty': { shortTitle: 'Rick and Morty сияқты', desc: 'Ғылыми сатира' },
  'anime': { shortTitle: 'Үздік аниме', desc: 'Жапон анимациясы' },
  'anime-shonen': { shortTitle: 'Naruto сияқты', desc: 'Сёнэн және шытырман' },
  'anime-shonen-pure': { shortTitle: 'Сёнэн', desc: 'Экшен және батыр өсуі' },
  'anime-isekai': { shortTitle: 'Исекай', desc: 'Басқа әлем' },
  'anime-romance': { shortTitle: 'Романтика', desc: 'Сезімдер және қарым-қатынас' },
  'anime-dark': { shortTitle: 'Қараңғы', desc: 'Психологиялық және қара' },
  'anime-seinen': { shortTitle: 'Сэйнэн', desc: 'Ересектер оқиғалары' },
  'anime-sports': { shortTitle: 'Спорт', desc: 'Жарыс және мінез' },
  'anime-fantasy': { shortTitle: 'Фэнтези', desc: 'Сиқыр және әлемдер' },
  'anime-school': { shortTitle: 'Мектеп', desc: 'Мектеп оқиғалары' },
  'anime-classic': { shortTitle: 'Классика', desc: 'Сыналған хиттер' },
  'anime-strong-hero': { shortTitle: 'Күшті батыр', desc: 'Өсу және күш' },
  'theme-space': { shortTitle: 'Ғарыш', desc: 'Жұлдыздар және галактикалар' },
  'theme-heist': { shortTitle: 'Ұрлықтар', desc: 'Жоспарлар және тәуекел' },
  'theme-maniac': { shortTitle: 'Маньяктар', desc: 'Психологиялық қорқыныш' },
  'theme-friendship': { shortTitle: 'Достық', desc: 'Байланыс және қолдау' },
  'theme-love': { shortTitle: 'Махаббат', desc: 'Сезімдер және қарым-қатынас' },
  'country-scandinavia': { shortTitle: 'Скандинавия', desc: 'Солтүстік Еуропа' },
  'country-europe': { shortTitle: 'Еуропа', desc: 'Еуропаның әртүрлі елдері' },
  'genre-боевик': { shortTitle: 'Боевиктер', desc: 'Экшен және динамика' },
  'genre-драма': { shortTitle: 'Драмалар', desc: 'Күшті оқиғалар' },
  'genre-комедия': { shortTitle: 'Комедиялар', desc: 'Күлкіге' },
  'genre-фантастика': { shortTitle: 'Фантастика', desc: 'Болашақ және басқа әлемдер' },
  'genre-триллер': { shortTitle: 'Триллерлер', desc: 'Шиеленіске ұстайды' },
  'genre-ужасы': { shortTitle: 'Қорқыныш', desc: 'Шынымен қорқынышты' },
  'genre-криминал': { shortTitle: 'Қылмыс', desc: 'Қылмыс және нуар' },
  'genre-мелодрама': { shortTitle: 'Романтика', desc: 'Махаббат туралы' },
  'genre-фэнтези': { shortTitle: 'Фэнтези', desc: 'Сиқыр және шытырман' },
  'genre-детектив': { shortTitle: 'Детективтер', desc: 'Жұмбақтар және тергеулер' },
  'genre-приключения': { shortTitle: 'Шытырман', desc: 'Үлкен шытырмандар' },
  'genre-мультфильм': { shortTitle: 'Мультфильмдер', desc: 'Барлығына арналған анимация' },
  'genre-история': { shortTitle: 'Тарихи', desc: 'Тарихқа негізделген' },
  'genre-военный': { shortTitle: 'Әскери', desc: 'Соғыс және адамдар' },
  'mood-light': { shortTitle: 'Жеңіл және жылы', desc: 'Кернеусіз' },
  'mood-tense': { shortTitle: 'Шиеленіс', desc: 'Триллерлер және интрига' },
  'mood-think': { shortTitle: 'Ойландырады', desc: 'Терең сюжеттер' },
  'mood-epic': { shortTitle: 'Эпикалық', desc: 'Көрнекті кино' },
  'mood-atmospheric': { shortTitle: 'Атмосфералық', desc: 'Әлемге бату' },
  'mood-calm': { shortTitle: 'Тыныш', desc: 'Асықпай' },
  'mood-dynamic': { shortTitle: 'Динамикалық', desc: 'Жылдам темп' },
  'mood-dark': { shortTitle: 'Қараңғы', desc: 'Ауыр атмосфера' },
  'country-KZ': { shortTitle: 'Қазақ', desc: 'Сапа бойынша топ' },
  'country-RU': { shortTitle: 'Орыс', desc: 'Сапа бойынша топ' },
  'country-IN': { shortTitle: 'Үнді', desc: 'Сапа бойынша топ' },
  'country-US': { shortTitle: 'Америкалық', desc: 'Сапа бойынша топ' },
  'country-KR': { shortTitle: 'Корей', desc: 'Сапа бойынша топ' },
  'country-JP': { shortTitle: 'Жапон', desc: 'Сапа бойынша топ' },
  'country-CN': { shortTitle: 'Қытай', desc: 'Сапа бойынша топ' },
  'country-FR': { shortTitle: 'Француз', desc: 'Сапа бойынша топ' },
  'country-GB': { shortTitle: 'Британ', desc: 'Сапа бойынша топ' },
  'country-TR': { shortTitle: 'Түрік', desc: 'Сапа бойынша топ' },
  'country-DE': { shortTitle: 'Неміс', desc: 'Сапа бойынша топ' },
  'country-ES': { shortTitle: 'Испан', desc: 'Сапа бойынша топ' }
};

export function getCollectionKkLabels(id) {
  return COLLECTION_LABELS_KK[id] || null;
}

export function getCollectionGroupKk(groupId) {
  return COLLECTION_GROUP_KK[groupId] || null;
}
